# Generated by Django 4.0.6 on 2022-07-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='posts_img/', verbose_name='Photo'),
        ),
    ]
